### ISSUE TITLE
Bug or Feature: Negative numbers apply healing instead of damage.

### ISSUE THREAD

**Issue by FurtherV** [krbz999/damage-application#2]
When dealing an negative amount of damage (or inputing a negative number into the dialog) the selected token is healed.
This might be intended behavior.

**Comment by InnilToo** [comment]
I feel like this is intended as positive (default) deals damage (does what you expect).
That said, the dialog could benefit from tooltips.

**Comment by krbz999** [comment]
There is no such thing as negative damage, so if a roll's total is negative, it should be treated as zero.

Additionally, seems terms preceded by a "-" were not treated as negative. Also fixed.
