### ISSUE TITLE
Complicated mathematical expression have wrong damage

### ISSUE THREAD

**Issue by FurtherV** [krbz999/damage-application#3]
When using a complicated formula for damage, the following cases seem to happen:

**Case 1:**
- `1d8 + @mod` Slashing damage
- `pow(2d6,2)` Fire damage
- Result: Both damages are counted as slashing damage

**Case 2:**
- `1d8 + @mod` Slashing damage
- `2d6*2` Fire damage
- Result: on a roll of 2 and 2, which should be (2+2)*2 = 4, the fire damage is counted as 6?

**None of these formulas are usually used in RAW / RAI D&D 5e though!**

**Comment by krbz999** [comment]
Damage rolls were a mistake.
